version: '3'

networks:
  backend:
    driver: bridge

services:
  # postgres
  database:
    container_name: '${DOCKER_CONTAINER_DB}'
    restart: always
    image: postgres:latest
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - backend
      - default
    profiles:
      - debug
      - stage
      - prod

  # REST API
  app:
    container_name: '${DOCKER_CONTAINER_APP}'
    build:
      context: ./
      dockerfile: ./.docker/app/Dockerfile
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/dist
      - /var/www/node_modules
      - resources:/resources:ro
    links:
      - database
    ports:
      - '${APP_PORT}:3000'
    networks:
      - backend
      - default
    profiles:
      - stage
      - prod

volumes:
  resources:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /
