version: '3'

services:
  # postgres
  database:
    container_name: '${DOCKER_CONTAINER_DB}'
    restart: always
    image: postgres:latest
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - default

volumes:
  resources:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /
